/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Rey
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    ArrayList<Kurs_Helper> matauang_item = new ArrayList<Kurs_Helper>();
    ArrayList<Stok_Helper> stok_item = new ArrayList<Stok_Helper>();
    DecimalFormat df = new DecimalFormat("#.##");

    public Transaksi() {
        initComponents();
        load_kurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_submit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tb_nik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_matauangawal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tb_nominal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_matauangtujuan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        bt_submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_submit.setText("Submit");
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaksi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Mata Uang Awal");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Nominal");

        tb_nominal.setText("0");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Mata Uang Tujuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cb_matauangtujuan, 0, 196, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_nominal)
                            .addComponent(cb_matauangawal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tb_nik)
                            .addComponent(tb_nama))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tb_nama)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_matauangawal, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tb_nominal, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_matauangtujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel6)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        // TODO add your handling code here:
        float hasil, hasil_temp, mu_awal, mu_tukar, temp_mu_tukar;
        int satuan_masuk, puluhan_masuk, ratusan_masuk;
        int satuan_keluar, puluhan_keluar, ratusan_keluar;
        hasil = 0;
        hasil_temp = 0;
        satuan_masuk = 0;
        puluhan_masuk = 0;
        ratusan_masuk = 0;
        satuan_keluar = 0;
        puluhan_keluar = 0;
        ratusan_keluar = 0;
        if (!tb_nik.getText().equalsIgnoreCase("")) {
            if (!tb_nama.getText().equalsIgnoreCase("")) {
                if (cb_matauangawal.getSelectedItem() != cb_matauangtujuan.getSelectedItem()) {
                    if (!tb_nominal.getText().equalsIgnoreCase("")) {
                        if (cb_matauangawal.getSelectedItem().equals("IDR") && !cb_matauangtujuan.getSelectedItem().equals("IDR")) {
                            if (Float.parseFloat(tb_nominal.getText()) >= 20000) {
                                hasil = Float.parseFloat(tb_nominal.getText()) / matauang_item.get(cb_matauangtujuan.getSelectedIndex()).kurs_jual;
                            } else {
                                JOptionPane.showMessageDialog(null, "Nominal penukaran minimal 20000 " + cb_matauangawal.getSelectedItem());
                            }
                        } else if (!cb_matauangawal.getSelectedItem().equals("IDR") && cb_matauangtujuan.getSelectedItem().equals("IDR")) {
                            if (Float.parseFloat(tb_nominal.getText()) >= 1) {
                                hasil = Float.parseFloat(tb_nominal.getText()) * matauang_item.get(cb_matauangawal.getSelectedIndex()).kurs_beli;
                            } else {
                                JOptionPane.showMessageDialog(null, "Nominal penukaran minimal 1 " + cb_matauangawal.getSelectedItem());
                            }
                        } else {
                            if (Float.parseFloat(tb_nominal.getText()) >= 1) {
                                hasil_temp = Float.parseFloat(tb_nominal.getText()) * matauang_item.get(cb_matauangawal.getSelectedIndex()).kurs_tengah;
                                hasil = hasil_temp / matauang_item.get(cb_matauangtujuan.getSelectedIndex()).kurs_tengah;
                            } else {
                                JOptionPane.showMessageDialog(null, "Nominal penukaran minimal 1 " + cb_matauangawal.getSelectedItem());
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Masukkan nominal yang benar!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mata uang yang ditukar tidak boleh sama!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "NIK tidak boleh kosong!");
        }
        mu_tukar = Float.parseFloat(df.format(hasil));
        mu_awal = Float.parseFloat(tb_nominal.getText());
        if (hasil != 0) {
            if (cb_matauangtujuan.getSelectedItem().equals("IDR")) {
                mu_tukar = mu_tukar / 1000;
            }
            temp_mu_tukar = mu_tukar;
            if (cb_matauangawal.getSelectedItem().equals("IDR")) {
                mu_awal = mu_awal / 1000;
            }
            ratusan_masuk = (int) mu_awal / 100;
            mu_awal = mu_awal % 100;
            puluhan_masuk = (int) mu_awal / 10;
            mu_awal = mu_awal % 10;
            satuan_masuk = (int) mu_awal / 1;
            if (temp_mu_tukar >= 100) {
                if (stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_ratusan != 0) {
                    ratusan_keluar = (int) temp_mu_tukar / 100;
                    temp_mu_tukar = temp_mu_tukar % 100;
                    if (ratusan_keluar > stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_ratusan) {
                        temp_mu_tukar = temp_mu_tukar + ((ratusan_keluar - stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_ratusan) * 100);
                        ratusan_keluar = stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_ratusan;
                    }
                } else {
                    ratusan_keluar = 0;
                }
            }
            if (temp_mu_tukar >= 10) {
                if (stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_puluhan != 0) {
                    puluhan_keluar = (int) temp_mu_tukar / 10;
                    temp_mu_tukar = temp_mu_tukar % 10;
                    if (puluhan_keluar > stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_puluhan) {
                        temp_mu_tukar = temp_mu_tukar + ((puluhan_keluar - stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_puluhan) * 10);
                        puluhan_keluar = stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_puluhan;
                    }
                } else {
                    puluhan_keluar = 0;
                }
            }
            if (temp_mu_tukar >= 1) {
                if (stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_satuan != 0) {
                    satuan_keluar = (int) temp_mu_tukar / 1;
                    if (satuan_keluar > stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_satuan) {
                        satuan_keluar = stok_item.get(cb_matauangtujuan.getSelectedIndex()).stok_satuan;
                    }
                } else {
                    satuan_keluar = 0;
                }
            }
            temp_mu_tukar = (ratusan_keluar * 100) + (puluhan_keluar * 10) + satuan_keluar;
            JOptionPane.showMessageDialog(this, hasil + " | " + mu_tukar + " | " + temp_mu_tukar);
            JOptionPane.showMessageDialog(this, "Keluar : " + ratusan_keluar + " | " + puluhan_keluar + " | " + satuan_keluar);
            JOptionPane.showMessageDialog(this, "Masuk : " + ratusan_masuk + " | " + puluhan_masuk + " | " + satuan_masuk);
            if (temp_mu_tukar == (int) mu_tukar) {
                try {
                    String sql_kurs = "INSERT INTO transaksi (NIK, NAMA, MATAUANG_AWAL, NOMINAL_AWAL,"
                            + " MATAUANG_TUKAR, NOMINAL_TUKAR) VALUES ('" + tb_nik.getText() + "','"
                            + tb_nama.getText() + "','" + cb_matauangawal.getSelectedItem() + "','"
                            + tb_nominal.getText() + "','" + cb_matauangtujuan.getSelectedItem() + "','"
                            + df.format(hasil) + "')";
                    String sql_stok_masuk = "UPDATE stok SET "
                            + "SATUAN='" + (stok_item.get(cb_matauangawal.getSelectedIndex()).stok_satuan + satuan_masuk)
                            + "', PULUHAN='" + (stok_item.get(cb_matauangawal.getSelectedIndex()).stok_puluhan + puluhan_masuk)
                            + "', RATUSAN='" + (stok_item.get(cb_matauangawal.getSelectedIndex()).stok_ratusan + ratusan_masuk) 
                            + "', WHERE ID_KURS='" + cb_matauangawal.getSelectedItem() + "'";
                    java.sql.Connection conn = (Connection) config.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql_kurs);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Penyimpanan data berhasil");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Stok kami tidak cukup");
            }
        }
    }//GEN-LAST:event_bt_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    private void load_kurs() {
        //menampilkan data database kedalam tabel
        try {
            String sql_matauang = "select * from kurs";
            String sql_stok = "select * from stok";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res;
            res = stm.executeQuery(sql_matauang);
            while (res.next()) {
                matauang_item.add(new Kurs_Helper(res.getString(1), Float.parseFloat(res.getString(2)), Float.parseFloat(res.getString(3)), Float.parseFloat(res.getString(4))));
            }
            res = stm.executeQuery(sql_stok);
            while (res.next()) {
                stok_item.add(new Stok_Helper(res.getString(1), Integer.parseInt(res.getString(2)), Integer.parseInt(res.getString(3)), Integer.parseInt(res.getString(4))));
            }
            for (Kurs_Helper item : matauang_item) {
                cb_matauangawal.addItem(item.mata_uang);
                cb_matauangtujuan.addItem(item.mata_uang);
            }
        } catch (Exception e) {
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_submit;
    private javax.swing.JComboBox<String> cb_matauangawal;
    private javax.swing.JComboBox<String> cb_matauangtujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_nik;
    private javax.swing.JTextField tb_nominal;
    // End of variables declaration//GEN-END:variables
}
